# host_vars/local/servers.yml
---
# COMMONS
id_image: "cb09f386-8235-4874-b7f4-4295edf5d73c"
id_network: "91af098d-c7c7-4882-a86b-1272fcdaf823"
flavor_normal: "m1.normal"
sshkey: "id_rsa"
# SERVERS
servers:
  - name: "dns"
    image_id: "{{ id_image }}"
    flavor: "{{ flavor_normal }}"
    sshkey_name: "{{ sshkey }}"
    nics:
      - network_id: "{{ id_network }}"
  - name: "apache"
    image_id: "{{ id_image }}"
    flavor: "{{ flavor_normal }}"
    sshkey_name: "{{ sshkey }}"
    nics:
      - network_id: "{{ id_network }}"
  - name: "mysql"
    image_id: "{{ id_image }}"
    flavor: "{{ flavor_normal }}"
    sshkey_name: "{{ sshkey }}"
    nics:
      - network_id: "{{ id_network }}"
  - name: "docker"
    image_id: "{{ id_image }}"
    flavor: "m1.large"
    sshkey_name: "{{ sshkey }}"
    nics:
      - network_id: "{{ id_network }}"
