# roles/hosting/tasks/config_docker.yml
---
- name: Create container for "{{ user_hosting }}"
  docker_container:
    name: "{{ user_hosting }}"
    image: "{{ cms_hosting }}"
    restart_policy: always
    state: started
    network_mode: "bridge"
    ports:
      "{{ port_hosting }}:80"
    comparisons:
      '*': strict
  become: false
