# roles/hosting/tasks/install_mysql.yml
---
#- name: Create Database for "{{ user_hosting }}"
#  mysql_db:
#    name: "{{ user_hosting }}"
#    state: present
#
#- name: Create database user "{{ user_hosting }}"
#  mysql_user:
#    name: "'{{ user_hosting }}'@'10.0.0.%'"
#    password: "{{ user_hosting }}"
#    priv: '{{ user_hosting }}.*:ALL'
#    state: present
- name: Create Database for "{{ user_hosting }}"
  command: mysql -u root -e "{{ item }}"
  with_items:
    - "CREATE DATABASE IF NOT EXISTS {{ user_hosting }};"
    - "CREATE USER IF NOT EXISTS '{{ user_hosting }}'@'10.0.0.%' IDENTIFIED BY '{{ user_hosting }}';"
    - "GRANT ALL PRIVILEGES ON {{ user_hosting }}.* TO '{{ user_hosting }}'@'10.0.0.%';"
