# roles/config/tasks/install_mysql.yml
---
- name: Install MySQL server
  apt:
    name: mysql-server
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Config MySQL server to be open in 0.0.0.0
  replace:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: '^bind-address.*'
    replace: 'bind-address = 0.0.0.0'

- name: Restart service MySQL
  systemd:
    name: mysql-server
    state: restarted
