# roles/config/tasks/install_docker.yml
---
- name: Install Docker
  include_role:
    name: geerlingguy.docker

- name: Install python3-pip
  apt:
    name: "python3-pip"
    state: present
    update_cache: yes
    force_apt_get: yes

- name: Install docker python3 module
  pip:
    name: "docker"
